chenge config
Serhii-Filatov/calculator pull request #3
Opened 2023-03-03 20:02 UTC by Serhii-Filatov

2023-03-07 14:55 UTC, Sk3ll commented
Change name of PR: feat/calculator/#1

2023-03-07 14:55 UTC, Sk3ll commented on package.json
> +    "format": "npx prettier . —write"
```suggestion
    "format": "npx prettier —write ."
```

2023-03-07 14:59 UTC, Sk3ll commented on src/index.css
> +*/
Вынести переиспользуемые значения в переменные

2023-03-07 14:59 UTC, Sk3ll commented on src/index.css
> +
не должно пробелов

2023-03-07 18:34 UTC, Serhii-Filatov commented on src/index.css
> +*/
Повторяющихся правил нет. Удалил комментарии с цветами из файла стилей. Закомитил это вместе с добавлением конфиг файла к линтеру. Перед тем запустил стайл линтер и пофиксил замечания что он выдал. Могу добавить переменные на случай изменений цвета или

2023-03-12 20:26 UTC, Sk3ll commented on src/view.js
> +  // eslint-disable-next-line no-restricted-syntax
read more about rule https://stackoverflow.com/questions/73127625/alternatives-for-using-forinstatement-is-not-allowed

better use destructing

2023-03-12 20:29 UTC, Sk3ll commented on src/view.js
> +  const calcScreen = document.createElement('div');
```suggestion
  const createComponent = ({ tagName, className, parentNode }) => {
    const node = document.createElement(tagName);
    node.className = className;
    parentNode.append(node);
    return node;
  }
```

Ты выносишь повторяещие элементы и можешь переисользовать такие функции, таким образом сократишь твой код

2023-03-12 20:46 UTC, Sk3ll commented
Please, rename pull request from "change config" to "feat/calculator/#1"

2023-03-12 21:05 UTC, Sk3ll commented on src/index.css
> +  background-color: #a6a6a6;
Use better css variables

2023-03-12 21:06 UTC, Sk3ll commented on src/view.js
> +function runView() {
```suggestion
const renderApp = () =>
```

2023-03-12 21:10 UTC, Sk3ll commented on src/view.js
> +function runView() {
`view.js` rename to `app.js`

2023-03-12 21:13 UTC, Sk3ll commented on .husky/pre-commit
> +npx stylelint '**/*.css'
По моему тут не запускаются твои скрипты, надо было писать так
```suggestion
npm run lint
npm run lint:html
nom run lint:style
```

2023-03-12 21:15 UTC, Sk3ll commented on src/index.css
> +  background-color: blanchedalmond;
Should use hex everywhere
Also use css variables for this

2023-03-17 11:10 UTC, Sk3ll commented on src/index.js
Все что ниже renderApp(); 
Вынеси в файл calculatorService.js и функции function clearAll() и  onclick = (event) => {
надо экспортировать и присвоить на кнопки в фукнции renderApp, когда ты их создаешь
Получается так, что мы перенесем всю логику в сервис и index.js у нас будет голенький с одной функцией = renderApp();

2023-03-17 11:12 UTC, Sk3ll commented on src/index.css
> +  box-shadow: 4px 4px 4px #4f4f4f;
Вынеси цвет в переменную

2023-03-17 11:12 UTC, Sk3ll commented on src/index.css
> +  color: #fff;
Вынеси цвет в переменную

2023-03-17 11:12 UTC, Sk3ll commented on src/index.css
> +  background-color: #000;
Вынеси цвет в переменную

2023-03-17 11:13 UTC, Sk3ll commented on src/index.css
> +  font-size: 2rem;
Использую или rem или px, чтоб была везде одна и таже шкала вычеслений

2023-03-17 11:44 UTC, Sk3ll commented on src/app.js
> +  }
const btn = createComponent({
  tagName: 'div',
  value: button.name,
  className: `btn ${button.class}`;,
  parentNode: numericBtn,
});

2023-03-17 11:44 UTC, Sk3ll commented on src/app.js
> +  calc.prepend(calcScreen);
const calcScreen = createComponent({
  tagName: 'div',
  className: ''calc-screen',
  parentNode: calc,
});

2023-03-17 11:48 UTC, Sk3ll commented on src/app.js
> +  calc.append(buttonsBlock);
```suggestion
buttonsBlock.onclick = calculate;
```

2023-03-17 18:00 UTC, Sk3ll commented on src/app.js
> +  const createComponent = (
Эту функцию мы можем вынести в `components/createComponent.js`

2023-03-17 18:02 UTC, Sk3ll commented on src/app.js
> +  const output = createComponent({
```suggestion
  createComponent({
```

you should use `eslint-disable-next-line no-unused-vars`

2023-03-30 08:22 UTC, Sk3ll commented on src/services/calculatorService.js
> +  out.textContent = '';
```suggestion
  setOutput('');
```

2023-03-30 08:23 UTC, Sk3ll commented on src/services/calculatorService.js
> +      out.textContent = a;
```suggestion
      setOutput(a);
```

2023-03-30 08:23 UTC, Sk3ll commented on src/services/calculatorService.js
> +      out.textContent = b;
```suggestion
      setOutput(b);
```

2023-03-30 08:23 UTC, Sk3ll commented on src/services/calculatorService.js
> +      out.textContent = b;
```suggestion
      setOutput(b);
```

2023-03-30 08:24 UTC, Sk3ll commented on src/services/calculatorService.js
> +    out.textContent = sign;
```suggestion
    setOutput(sign);
```

2023-03-30 08:24 UTC, Sk3ll commented on src/services/calculatorService.js
> +    out.textContent = a;
```suggestion
    setOutput(a);
```

2023-04-10 15:49 UTC, Sk3ll requested changes

2023-04-10 15:49 UTC, Sk3ll commented on src/services/calculatorService.js
> +      setState({ isFinished: false });
```suggestion
      setState({ secondNumber: key, isFinished: false });
```

2023-04-10 15:49 UTC, Sk3ll commented on src/services/calculatorService.js
> +      state.secondNumber += key;
```suggestion
setState({ secondNumber: state.secondNumber + key });
```

2023-04-10 15:49 UTC, Sk3ll commented on src/services/calculatorService.js
> +  if (key === '=') {
```suggestion
  if (isEqualOperation(key)) {
```

2023-04-10 15:49 UTC, Sk3ll commented on src/services/calculatorService.js
> +    if (isEmpty(state.secondNumber)) state.secondNumber = state.firstNumber;
```suggestion
if (isEmpty(state.secondNumber)) {
  setState({ secondNumber: state.firstNumber });
}
```

2023-04-10 15:49 UTC, Sk3ll commented on src/utils/helpers.js
> +export const convert = (value) => value * 2;
export const convert = (value) => value * 2;

bad practice

2023-04-11 18:39 UTC, Sk3ll requested changes

2023-04-11 18:39 UTC, Sk3ll commented on src/services/calculatorService.js
> +        state.firstNumber -= (state.firstNumber * REVERS);
```suggestion
        setState({ firstNumber: state.firstNumber - (state.firstNumber * REVERS) });
```

2023-04-11 18:39 UTC, Sk3ll commented on src/services/calculatorService.js
> +        state.firstNumber *= PERCENT;
```suggestion
        setState({ firstNumber: state.firstNumber * PERCENT });
```

2023-04-11 18:39 UTC, Sk3ll commented on src/services/calculatorService.js
> +const actions = ['-', '+', '*', '/', '+/-', '%'];
```suggestion
const actions = {
  MINUS: '-',
  PLUS: '+',
  MULTIPLE: '*',
  DIVIDE:  '/',
  PLUS_MINUS: '+/-',
  PERCENT:  '%',
};
```

2023-04-11 18:39 UTC, Sk3ll commented on src/services/calculatorService.js
> +  if (actions.includes(key)) {
```suggestion
  if (Object.values(actions).includes(key)) {
```

2023-04-11 18:39 UTC, Sk3ll commented on src/services/calculatorService.js
> +      case '+':
```suggestion
      case actions.PLUS:
```

2023-04-11 18:39 UTC, Sk3ll commented on src/services/calculatorService.js
> +      case '-':
```suggestion
      case actions.MINUS:
```

2023-04-11 18:39 UTC, Sk3ll commented on src/services/calculatorService.js
> +const clearArg = {
```suggestion
const defaultState = {
```

И перенеси её в `store`
и там сделай 
`const state = defaultState;`
А потом меняй именно state уже, как обычно

2023-04-13 08:18 UTC, Sk3ll commented on src/store/calculatorStore.js
> +export const state = defaultState;
```suggestion
export const state = { ...defaultState };
```

2023-04-13 22:12 UTC, Sk3ll commented on src/services/calculatorService.js
> +  setOutput('0');
```suggestion
  setOutput(defaultState.out);
```

2023-04-13 22:13 UTC, Sk3ll commented on src/services/calculatorService.js
> +};
PERCENTAGE, REVERS, digits, actions 
вынести в папку utils/constants.js

2023-04-13 22:14 UTC, Sk3ll commented on src/services/calculatorService.js
> +          setOutput('Ошибка!');
```suggestion
          setOutput(ERROR_TEXT);
```
вынести в `constants.js`

2023-04-14 10:21 UTC, Sk3ll approved these changes

2023-04-14 10:21 UTC, merged